var name = "Bob";
int messages = 3;
decimal temperature = 34.4m;
Console.Write("Hello, ");
Console.Write(name);
Console.Write("! You have ");
Console.Write(messages);
Console.Write(" messages in you inbox. The temperature is ");
Console.Write(temperature);
Console.Write(" Celsius.");